# Generated by Django 2.2 on 2020-03-28 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='token',
            new_name='Fcm_Token',
        ),
    ]
