# Generated by Django 2.2 on 2020-03-28 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20200328_1132'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fcm_Token',
            new_name='Token',
        ),
    ]
